### ISSUE TITLE
symfony/psr-http-message-bridge versions

### ISSUE THREAD

**Issue by Punt13140** [loophp/psr-http-message-bridge-bundle#82]
Hello,

Shouldn't this package support the new “symfony/psr-http-message-bridge” tag versioning that follows Symfony versions ?

Thanks

**Comment by drupol** [comment]
Hello !

Yes it should, I should dedicate some time to this library at work, but I got busy with other tasks not related to PHP lately.

Are you willing to help by submitting a PR ?

**Comment by Punt13140** [comment]
Unfortunately I'm very busy this month. In July I might have some time.
I'll keep an eye on this issue and I'll let you know if I can submit a PR.
